### PR TITLE
Setup for Portfolio Website Project

### PR DESCRIPTION
**Pull request by MustafaSamiShirzad**
In this file following changes were done:

- [ ] Added HTML
- [ ] Added CSS
- [ ] Added README
- [ ] And other Project supported Documents.

### CODE REVIEW

**Review by Gambit142 — COMMENTED** [review]
Hi @MustafaSamiShirzad 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that the most of the information in the README contains details of the Hello Microverse Project. Kindly change the information to suit the portfolio project. 👍 😎

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Gambit142 — COMMENTED** [review]
Hi @MustafaSamiShirzad 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- The link that you provided to clone this project is that of the Hello World project. 
- Kindly fill the install section of the README with the appropriate information. You can include ways to install npm or the linters configuration that you have. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by LionRouge1 — COMMENTED** [review]
Hi @MustafaSamiShirzad, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a README file that doesn't have all the sections in the recommended Microverse [README template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Zuhaib042 — COMMENTED** [review]
Hi @MustafaSamiShirzad  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that diesnt have a professional name for the feature branch. your feature branch should have the name for a feature that you are applying in that pull request or name of the action that you are doing in that pull request. 
for example in your project, you can name your feature branch as `setup-mobile-first` or `mobile_first_hero_section`. 
- [ ] Now what you can do is checkout from your feature branch to a new branch by using this command `git checkout -b setup-mobile-first` and then from that branch, make a pull request to the main branch and submit that PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by LionRouge1 — COMMENTED** [review]
Hi @MustafaSamiShirzad, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that doesn't follow GitHub flow (Your branch name should have a feature or action name (e.g. "setup_mobile_first" or "mobile_first"). Kindly create a new branch with a semantic name representing what is in the branch and refer to this PR in the new PR that you will create. Or read this [article](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) about how to rename a branch name.
- [ ] Kindly make sure that your README file has all the sections in the recommended Microverse [README template](https://github.com/microverseinc/readme-template), only the :question: FAQ (OPTIONAL) section is optional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MustafaSamiShirzad** [comment]
kindly review that changes i have done

**Pull request closed without merging**
